Adding CONTRIBUTING.md file
SamDev98/password-manager-py pull request #11
Opened 2021-03-11 03:54 UTC by SamDev98

* This is the initial draft for the file
* Suggestions are welcome! :)

2021-03-11 06:15 UTC, nhcarrigan requested changes

2021-03-11 06:15 UTC, nhcarrigan commented on CONTRIBUTING.md
> +method with the owners of this repository before making a change.
I recommend removing the email. Keep the discussions scoped to the repository so other contributors are not excluded.

2021-03-11 06:15 UTC, nhcarrigan commented on CONTRIBUTING.md
> +Please note we have a code of conduct, please follow it in all your interactions with the project.
See my comment below. This should link to the code of conduct file.

2021-03-11 06:15 UTC, nhcarrigan commented on CONTRIBUTING.md
> +3. You may merge the Pull Request in once you have the sign-off of the code-owner.
So anyone can merge a pull request?

```suggestion
3. Once a pull request is approved by the code owners, a maintainer will merge it.
```

2021-03-11 06:15 UTC, nhcarrigan commented on CONTRIBUTING.md
> +[version]: http://contributor-covenant.org/version/2/0/
This should go in a `CODE_OF_CONDUCT.md` file, separate from your contributing doc.

2021-03-11 08:06 UTC, SamDev98 commented on CONTRIBUTING.md
> +method with the owners of this repository before making a change.
Okay, please check my latest commit, I hope i have resolved these correctly.

2021-03-11 08:07 UTC, SamDev98 commented
@nhcarrigan I hope the changes are good now?

2021-03-11 08:55 UTC, jai-dewani commented on CONTRIBUTING.md
> +2. It can be found in the [README](Tk_README.md) for the tkinter-based application.
Instead of just the `README` I think you can point to a specific section of the readme as `README.MD#section-name` for the installation process.  

A personal view, but you can create a separate section for installation and running the application instead of having it under documentation or maybe give it a heading just to make it more visible and also include the step installing all dependencies using `pip install requirements.txt` because not everyone will not know that

2021-03-11 09:02 UTC, SamDev98 commented on CONTRIBUTING.md
> +2. It can be found in the [README](Tk_README.md) for the tkinter-based application.
Basically, all of the steps in Tk_README have to be followed regardless of the fact if this is to set up as a user application or for a developer, so I haven't tagged a particular header.

About the other point, do you mean I should give specific commands in the readme? Since I have linked the docs where they explain the procedure to install it.

2021-03-11 09:22 UTC, SamDev98 commented
@jai-dewani I took your comments into consideration and have made the changes, please let me know if this is okay.

2021-03-11 09:31 UTC, jai-dewani approved these changes
LGTM!

2021-03-11 11:25 UTC, merged

2021-03-16 16:49 UTC, SamDev98 commented
Thank you everyone for contributing! @all-contributors please add @jai-dewani  for ideas

2021-03-16 16:49 UTC, SamDev98 commented
@all-contributors please add @nhcarrigan  for doc